### ISSUE TITLE
FullNodeTest/light_node crashing sometimes

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/taraxa-node#1661] opened 2022-03-28 10:57 UTC
```
0x0000000306d34000 de2b1203… PBFT_CHAIN [2022-03-28 12:51:02.144580] ERROR: Cannot find PBFT block hash #d8db772d… in DB
0x0000000306d34000 de2b1203… PBFT_CHAIN [2022-03-28 12:51:02.144580] ERROR: Cannot find PBFT block hash #d8db772d… in DB
Assertion failed: (false), function getPbftBlockInChain, file pbft_chain.cpp, line 80.
fish: Job 1, './bin/full_node_test --gtest_fi…' terminated by signal SIGABRT (Abort)
```

**Comment by MatusKysel** [comment] 2022-03-28 11:08
duplicate of https://github.com/Taraxa-project/taraxa-node/issues/1651

**Closed** 2022-03-28 11:23 UTC
